// GlobalComponents for Volar
declare module 'vue' {
  export interface GlobalComponents {
    ElAffix: typeof import('park-ui')['ElAffix']
    ElAlert: typeof import('park-ui')['ElAlert']
    ElAside: typeof import('park-ui')['ElAside']
    ElAutocomplete: typeof import('park-ui')['ElAutocomplete']
    ElAvatar: typeof import('park-ui')['ElAvatar']
    ElBacktop: typeof import('park-ui')['ElBacktop']
    ElBadge: typeof import('park-ui')['ElBadge']
    ElBreadcrumb: typeof import('park-ui')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('park-ui')['ElBreadcrumbItem']
    ElButton: typeof import('park-ui')['ElButton']
    ElButtonGroup: typeof import('park-ui')['ElButtonGroup']
    ElCalendar: typeof import('park-ui')['ElCalendar']
    ElCard: typeof import('park-ui')['ElCard']
    ElCarousel: typeof import('park-ui')['ElCarousel']
    ElCarouselItem: typeof import('park-ui')['ElCarouselItem']
    ElCascader: typeof import('park-ui')['ElCascader']
    ElCascaderPanel: typeof import('park-ui')['ElCascaderPanel']
    ElCheckbox: typeof import('park-ui')['ElCheckbox']
    ElCheckboxButton: typeof import('park-ui')['ElCheckboxButton']
    ElCheckboxGroup: typeof import('park-ui')['ElCheckboxGroup']
    ElCol: typeof import('park-ui')['ElCol']
    ElCollapse: typeof import('park-ui')['ElCollapse']
    ElCollapseItem: typeof import('park-ui')['ElCollapseItem']
    ElCollapseTransition: typeof import('park-ui')['ElCollapseTransition']
    ElColorPicker: typeof import('park-ui')['ElColorPicker']
    ElContainer: typeof import('park-ui')['ElContainer']
    ElConfigProvider: typeof import('park-ui')['ElConfigProvider']
    ElDatePicker: typeof import('park-ui')['ElDatePicker']
    ElDialog: typeof import('park-ui')['ElDialog']
    ElDivider: typeof import('park-ui')['ElDivider']
    ElDrawer: typeof import('park-ui')['ElDrawer']
    ElDropdown: typeof import('park-ui')['ElDropdown']
    ElDropdownItem: typeof import('park-ui')['ElDropdownItem']
    ElDropdownMenu: typeof import('park-ui')['ElDropdownMenu']
    ElEmpty: typeof import('park-ui')['ElEmpty']
    ElFooter: typeof import('park-ui')['ElFooter']
    ElForm: typeof import('park-ui')['ElForm']
    ElFormItem: typeof import('park-ui')['ElFormItem']
    ElHeader: typeof import('park-ui')['ElHeader']
    ElIcon: typeof import('park-ui')['ElIcon']
    ElImage: typeof import('park-ui')['ElImage']
    ElImageViewer: typeof import('park-ui')['ElImageViewer']
    ElInput: typeof import('park-ui')['ElInput']
    ElInputNumber: typeof import('park-ui')['ElInputNumber']
    ElLink: typeof import('park-ui')['ElLink']
    ElMain: typeof import('park-ui')['ElMain']
    ElMenu: typeof import('park-ui')['ElMenu']
    ElMenuItem: typeof import('park-ui')['ElMenuItem']
    ElMenuItemGroup: typeof import('park-ui')['ElMenuItemGroup']
    ElOption: typeof import('park-ui')['ElOption']
    ElOptionGroup: typeof import('park-ui')['ElOptionGroup']
    ElPageHeader: typeof import('park-ui')['ElPageHeader']
    ElPagination: typeof import('park-ui')['ElPagination']
    ElPopconfirm: typeof import('park-ui')['ElPopconfirm']
    ElPopper: typeof import('park-ui')['ElPopper']
    ElProgress: typeof import('park-ui')['ElProgress']
    ElRadio: typeof import('park-ui')['ElRadio']
    ElRadioButton: typeof import('park-ui')['ElRadioButton']
    ElRadioGroup: typeof import('park-ui')['ElRadioGroup']
    ElRate: typeof import('park-ui')['ElRate']
    ElRow: typeof import('park-ui')['ElRow']
    ElScrollbar: typeof import('park-ui')['ElScrollbar']
    ElSelect: typeof import('park-ui')['ElSelect']
    ElSlider: typeof import('park-ui')['ElSlider']
    ElStep: typeof import('park-ui')['ElStep']
    ElSteps: typeof import('park-ui')['ElSteps']
    ElSubMenu: typeof import('park-ui')['ElSubMenu']
    ElSwitch: typeof import('park-ui')['ElSwitch']
    ElTabPane: typeof import('park-ui')['ElTabPane']
    ElTable: typeof import('park-ui')['ElTable']
    ElTableColumn: typeof import('park-ui')['ElTableColumn']
    ElTabs: typeof import('park-ui')['ElTabs']
    ElTag: typeof import('park-ui')['ElTag']
    ElTimePicker: typeof import('park-ui')['ElTimePicker']
    ElTimeSelect: typeof import('park-ui')['ElTimeSelect']
    ElTimeline: typeof import('park-ui')['ElTimeline']
    ElTimelineItem: typeof import('park-ui')['ElTimelineItem']
    ElTooltip: typeof import('park-ui')['ElTooltip']
    ElTransfer: typeof import('park-ui')['ElTransfer']
    ElTree: typeof import('park-ui')['ElTree']
    ElTreeV2: typeof import('park-ui')['ElTreeV2']
    ElUpload: typeof import('park-ui')['ElUpload']
    ElSpace: typeof import('park-ui')['ElSpace']
    ElSkeleton: typeof import('park-ui')['ElSkeleton']
    ElSkeletonItem: typeof import('park-ui')['ElSkeletonItem']
    ElCheckTag: typeof import('park-ui')['ElCheckTag']
    ElDescriptions: typeof import('park-ui')['ElDescriptions']
    ElDescriptionsItem: typeof import('park-ui')['ElDescriptionsItem']
    ElResult: typeof import('park-ui')['ElResult']
    ElSelectV2: typeof import('park-ui')['ElSelectV2']
  }
}

declare module '@vue/runtime-core' {
  interface ComponentCustomProperties {
    $message: typeof import('park-ui')['ElMessage']
    $notify: typeof import('park-ui')['ElNotification']
    $msgbox: typeof import('park-ui')['ElMessageBox']
    $messageBox: typeof import('park-ui')['ElMessageBox']
    $alert: typeof import('park-ui')['ElMessageBox']['alert']
    $confirm: typeof import('park-ui')['ElMessageBox']['confirm']
    $prompt: typeof import('park-ui')['ElMessageBox']['prompt']
    $loading: typeof import('park-ui')['ElLoadingService']
  }
}

export {}
